//go:build !ignore_autogenerated

/*
Copyright 2024 SUSE LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProductClassInfo) DeepCopyInto(out *ProductClassInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProductClassInfo.
func (in *ProductClassInfo) DeepCopy() *ProductClassInfo {
	if in == nil {
		return nil
	}
	out := new(ProductClassInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProductRegistrationSpec) DeepCopyInto(out *ProductRegistrationSpec) {
	*out = *in
	if in.RegistrationRequest != nil {
		in, out := &in.RegistrationRequest, &out.RegistrationRequest
		*out = new(RegistrationRequest)
		(*in).DeepCopyInto(*out)
	}
	if in.OfflineRegistrationCertificateSecretRef != nil {
		in, out := &in.OfflineRegistrationCertificateSecretRef, &out.OfflineRegistrationCertificateSecretRef
		*out = new(corev1.SecretReference)
		**out = **in
	}
	if in.SyncNow != nil {
		in, out := &in.SyncNow, &out.SyncNow
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProductRegistrationSpec.
func (in *ProductRegistrationSpec) DeepCopy() *ProductRegistrationSpec {
	if in == nil {
		return nil
	}
	out := new(ProductRegistrationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProductRegistrationStatus) DeepCopyInto(out *ProductRegistrationStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RegistrationProcessedTS != nil {
		in, out := &in.RegistrationProcessedTS, &out.RegistrationProcessedTS
		*out = (*in).DeepCopy()
	}
	if in.SCCSystemID != nil {
		in, out := &in.SCCSystemID, &out.SCCSystemID
		*out = new(int)
		**out = **in
	}
	if in.RegisteredProduct != nil {
		in, out := &in.RegisteredProduct, &out.RegisteredProduct
		*out = new(string)
		**out = **in
	}
	if in.RegistrationExpiresAt != nil {
		in, out := &in.RegistrationExpiresAt, &out.RegistrationExpiresAt
		*out = (*in).DeepCopy()
	}
	in.ActivationStatus.DeepCopyInto(&out.ActivationStatus)
	if in.SystemCredentialsSecretRef != nil {
		in, out := &in.SystemCredentialsSecretRef, &out.SystemCredentialsSecretRef
		*out = new(corev1.SecretReference)
		**out = **in
	}
	if in.OfflineRegistrationRequest != nil {
		in, out := &in.OfflineRegistrationRequest, &out.OfflineRegistrationRequest
		*out = new(corev1.SecretReference)
		**out = **in
	}
	if in.SubscriptionInfo != nil {
		in, out := &in.SubscriptionInfo, &out.SubscriptionInfo
		*out = new(SubscriptionMetadata)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProductRegistrationStatus.
func (in *ProductRegistrationStatus) DeepCopy() *ProductRegistrationStatus {
	if in == nil {
		return nil
	}
	out := new(ProductRegistrationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegistrationRequest) DeepCopyInto(out *RegistrationRequest) {
	*out = *in
	if in.RegistrationCodeSecretRef != nil {
		in, out := &in.RegistrationCodeSecretRef, &out.RegistrationCodeSecretRef
		*out = new(corev1.SecretReference)
		**out = **in
	}
	if in.RegistrationAPIUrl != nil {
		in, out := &in.RegistrationAPIUrl, &out.RegistrationAPIUrl
		*out = new(string)
		**out = **in
	}
	if in.RegistrationAPICertificateSecretRef != nil {
		in, out := &in.RegistrationAPICertificateSecretRef, &out.RegistrationAPICertificateSecretRef
		*out = new(corev1.SecretReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegistrationRequest.
func (in *RegistrationRequest) DeepCopy() *RegistrationRequest {
	if in == nil {
		return nil
	}
	out := new(RegistrationRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionMetadata) DeepCopyInto(out *SubscriptionMetadata) {
	*out = *in
	if in.StartsAt != nil {
		in, out := &in.StartsAt, &out.StartsAt
		*out = (*in).DeepCopy()
	}
	if in.ExpiresAt != nil {
		in, out := &in.ExpiresAt, &out.ExpiresAt
		*out = (*in).DeepCopy()
	}
	if in.ProductClasses != nil {
		in, out := &in.ProductClasses, &out.ProductClasses
		*out = make([]ProductClassInfo, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionMetadata.
func (in *SubscriptionMetadata) DeepCopy() *SubscriptionMetadata {
	if in == nil {
		return nil
	}
	out := new(SubscriptionMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemActivationState) DeepCopyInto(out *SystemActivationState) {
	*out = *in
	if in.LastValidatedTS != nil {
		in, out := &in.LastValidatedTS, &out.LastValidatedTS
		*out = (*in).DeepCopy()
	}
	if in.SystemURL != nil {
		in, out := &in.SystemURL, &out.SystemURL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemActivationState.
func (in *SystemActivationState) DeepCopy() *SystemActivationState {
	if in == nil {
		return nil
	}
	out := new(SystemActivationState)
	in.DeepCopyInto(out)
	return out
}
