// Code generated by github.com/SUSE/connect-ng/k8s/cmd/generate. DO NOT EDIT.
//
// This file is regenerated whenever you run the generator.
// To add custom helpers or constants, create a separate file (e.g., productregistration_helpers.go)
// that will not be overwritten.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	// Import common Spec/Status types from the library
	connectngv1 "github.com/SUSE/connect-ng/k8s/api/v1"
	"github.com/SUSE/connect-ng/k8s/types"
)

// Condition types - re-exported from library for convenience
const (
	// General conditions
	ConditionTypeReady       = connectngv1.ConditionTypeReady
	ConditionTypeDone        = connectngv1.ConditionTypeDone
	ConditionTypeProgressing = connectngv1.ConditionTypeProgressing
	ConditionTypeFailure     = connectngv1.ConditionTypeFailure

	// Registration conditions
	ConditionTypeAnnounced = connectngv1.ConditionTypeAnnounced
	ConditionTypeURLReady  = connectngv1.ConditionTypeURLReady
	ConditionTypeActivated = connectngv1.ConditionTypeActivated
	ConditionTypeKeepalive = connectngv1.ConditionTypeKeepalive

	// Offline conditions
	ConditionTypeOfflineRequestReady     = connectngv1.ConditionTypeOfflineRequestReady
	ConditionTypeOfflineCertificateReady = connectngv1.ConditionTypeOfflineCertificateReady
	ConditionTypeOfflineActivationDone   = connectngv1.ConditionTypeOfflineActivationDone
)

// +kubebuilder:object:root=true
// +kubebuilder:resource:scope=Cluster
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Activated",type=boolean,JSONPath=`.status.activated`
// +kubebuilder:printcolumn:name="System ID",type=integer,JSONPath=`.status.sccSystemID`
// +kubebuilder:printcolumn:name="Last Sync",type="date",JSONPath=".status.lastSync"

// ProductRegistration is the Schema for the productregistrations API.
// It embeds the common Spec and Status types from the library.
type ProductRegistration struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   connectngv1.ProductRegistrationSpec   `json:"spec,omitempty"`
	Status connectngv1.ProductRegistrationStatus `json:"status,omitempty"`
}

// Interface implementation for types.ProductRegistrationObject

// GetSpec returns the spec as the interface type.
// This allows the library controller to work with any product's CRD.
func (pr *ProductRegistration) GetSpec() types.ProductRegistrationSpec {
	return &pr.Spec
}

// GetStatus returns the status as the interface type.
// This allows the library controller to work with any product's CRD.
func (pr *ProductRegistration) GetStatus() types.ProductRegistrationStatus {
	return &pr.Status
}

// Convenience methods that delegate to the embedded Status

// HasCondition checks if a condition of the given type exists
func (pr *ProductRegistration) HasCondition(condType string) bool {
	return pr.Status.HasCondition(condType)
}

// GetCondition returns the condition with the given type, or nil if not found
func (pr *ProductRegistration) GetCondition(condType string) *metav1.Condition {
	return pr.Status.GetCondition(condType)
}

// IsConditionTrue returns true if the condition exists and its status is True
func (pr *ProductRegistration) IsConditionTrue(condType string) bool {
	return pr.Status.IsConditionTrue(condType)
}

// SetCondition adds or updates a condition
func (pr *ProductRegistration) SetCondition(condType string, status metav1.ConditionStatus, reason, message string) {
	pr.Status.SetCondition(condType, status, reason, message)
}

// +kubebuilder:object:root=true

// ProductRegistrationList contains a list of ProductRegistration
type ProductRegistrationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ProductRegistration `json:"items"`
}
