// Code generated by github.com/SUSE/connect-ng/k8s/codegen. DO NOT EDIT.

// Package v1 contains the v1 API for rancher product registration.
//
// This package defines the Kubernetes Custom Resource Definition (CRD) for
// ProductRegistration resources in the rancher.registration.suse.com API group.
//
// The types in this package are generated from github.com/SUSE/connect-ng/k8s
// templates and embed common Spec/Status types from that library.
//
// After generating these types, run controller-gen to generate DeepCopy methods and CRD manifests:
//
//   controller-gen object:headerFile=hack/boilerplate.go.txt paths=./apis/...
//   controller-gen crd:crdVersions=v1 paths=./apis/... output:crd:dir=config/crd/bases
//
// +k8s:openapi-gen=true
// +k8s:deepcopy-gen=package
// +kubebuilder:object:generate=true
// +groupName=rancher.registration.suse.com
package v1

import (
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
)

var (
	// SchemeGroupVersion is group version used to register these objects
	SchemeGroupVersion = schema.GroupVersion{Group: "rancher.registration.suse.com", Version: "v1"}

	// SchemeBuilder is used to add go types to the GroupVersionKind scheme
	SchemeBuilder = runtime.NewSchemeBuilder(addKnownTypes)

	// AddToScheme adds the types in this group-version to the given scheme.
	AddToScheme = SchemeBuilder.AddToScheme
)

// addKnownTypes adds the set of types defined in this package to the supplied scheme.
func addKnownTypes(scheme *runtime.Scheme) error {
	scheme.AddKnownTypes(SchemeGroupVersion,
		&ProductRegistration{},
	)
	return nil
}
