// Code generated by github.com/SUSE/connect-ng/k8s/cmd/generate. DO NOT EDIT.

// Package v1 contains the v1 API for rancher product registration.
//
// This package defines the Kubernetes Custom Resource Definition (CRD) for
// ProductRegistration resources in the rancher.registration.suse.com API group.
//
// The types in this package are generated from github.com/SUSE/connect-ng/k8s
// templates and import common functionality from that library. The registration
// controller logic is provided by github.com/SUSE/connect-ng/k8s/registration.
//
// +kubebuilder:object:generate=true
package v1
